#!/usr/bin/env bash

set -e

if [ -e .version ]; then
  rm .version
fi

RESULT=$(cat ../README.md| grep '^    \$ semver' | sed -e 's#    \$ #../src/#' | xargs -L1 bash)
EXPECT=$(cat ../README.md| grep '^    [^a-zA-Z$ ]' |grep -v '^    \$ semver' | sed -e 's#^    ##')

if [[ "$RESULT" != "$EXPECT" ]]; then
  exit 1
fi

rm -f .version
