name: Unit Tests and Linters

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-lint:
    name: Test and Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test stable
        run: make test-stable
